### ISSUE TITLE
Unable to handle multiple domains

### ISSUE THREAD

**Issue by philross88** [shogo82148/acme-cert-updater#33]
I was testing this code as I needed something similar. I found that the python crashes if you add multiple domains separated by comma whereas it seems like the code supports it since it uses for the domain in domains and parsing multiple domains. The crash happens in the savecert function when it tries to write the files -- may be because the directory doesn't exist.

`DEBUG:s3transfer.tasks:Executing task UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x1060d0450>}) with kwargs {'client': <botocore.client.S3 object at 0x105b040d0>, 'config': <boto3.s3.transfer.TransferConfig object at 0x105e01c10>, 'osutil': <s3transfer.utils.OSUtils object at 0x1060d0c10>, 'request_executor': <s3transfer.futures.BoundedExecutor object at 0x1060d0950>, 'transfer_future': <s3transfer.futures.TransferFuture object at 0x1060d0450>}
DEBUG:s3transfer.tasks:Exception raised.
Traceback (most recent call last):
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/upload.py", line 549, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/upload.py", line 237, in provide_transfer_size
    transfer_future.meta.call_args.fileobj))
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/utils.py", line 243, in get_file_size
    return os.path.getsize(filename)
  File "/Users/phil/.pyenv/versions/3.7.4/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/t2/tsb1dh4568d1vx_1n9vxr4h40000gn/T/tmpw9ckmhcp/config-dir/live/jojo.blahblah.com/cert.pem'
DEBUG:s3transfer.utils:Releasing acquire 0/None
DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "orig-app.py", line 331, in <module>
    lambda_handler({}, None)
  File "orig-app.py", line 325, in lambda_handler
    certonly(config)
  File "orig-app.py", line 118, in certonly
    save_cert(config, tmp)
  File "orig-app.py", line 164, in save_cert
    build_key(config.prefix, domain, now, filename),
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/boto3/s3/inject.py", line 209, in bucket_upload_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/upload.py", line 549, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/Users/phil/Documents//blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/upload.py", line 237, in provide_transfer_size
    transfer_future.meta.call_args.fileobj))
  File "/Users/phil/Documents/blahblah/blahblah /Website/NewSite/Lambda Functions/CertBot/s3transfer/utils.py", line 243, in get_file_size
    return os.path.getsize(filename)
  File "/Users/phil/.pyenv/versions/3.7.4/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/t2/tsb1dh4568d1vx_1n9vxr4h40000gn/T/tmpw9ckmhcp/config-dir/live/jojo.blahblah.com/cert.pem'
ERROR:certbot._internal.log:An unexpected error occurred:
An unexpected error occurred:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/t2/tsb1dh4568d1vx_1n9vxr4h40000gn/T/tmpw9ckmhcp/config-dir/live/jojo.blahblah.com/cert.pem'
Please see the logfile '/var/folders/t2/tsb1dh4568d1vx_1n9vxr4h40000gn/T/tmpw9ckmhcp/logs-dir' for more details.
Qualys:CertBot phil$ 
`

**Comment by shogo82148** [comment]
thanks for your report!
can I have your domain names you tested?

**Comment by philross88** [comment]
Sorry I can't share the domain name but you can try any domain with comma seperation. What i found is that if you add multiple domains, it won't get multiple certs but a same cert with multiple domains. You can both use cases so for my use case I modified the function differently.

BTW, how do you turn off the logging. I set the logging.basicConfig(level=logging.CRITICAL) and it's still showing Debug logs from Certbot. Which means if you switch to prod, your certs would be logged into the cloudtrial.

**Comment by shogo82148** [comment]
it looks that certbot overwrites the log level by its arguments.

https://github.com/certbot/certbot/blob/9cbb13ef041cb16c668f6644d132fcd738488798/certbot/certbot/_internal/log.py#L111-L115

**Comment by philross88** [comment]
I have tried passing --quiet and it seems like some of messages with DEBUG got suppressed however, still a lot of AWS messages are being logged with security tokens for S3 upload etc.

**Comment by philross88** [comment]
One more update --quiet didn't work. That was something else I put in place to suppress the logs

**Comment by shogo82148** [comment]
I just released https://github.com/shogo82148/acme-cert-updater/releases/tag/v0.0.17
It can handle multiple domains.
If you want to get multiple certs, please add [AWS::Events::Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html) into your cloudformation template.

I moved logging problem to https://github.com/shogo82148/acme-cert-updater/issues/41
